minor changes

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -48,14 +48,15 @@ system_install() {
 }
 
 pixi_install() {
+  has_cmd pixi && return 0
+
   has_cmd curl || die "curl is not installed. Quitting."
+  echo "pixi is not installed. Installing pixi."
+  curl -fsSL https://pixi.sh/install.sh | sh
+  has_cmd pixi || die "Failed to install pixi"
+}
 
-  has_cmd pixi || {
-    echo "pixi is not installed. Installing pixi."
-    curl -fsSL https://pixi.sh/install.sh | sh
-    has_cmd pixi || die "Failed to install pixi"
-  }
-
+pixi_packages_install() {
   pixi global install bat bottom carapace direnv duf eza fd fzf gdu gh \
     jq nushell xh ripgrep tealdeer television trash-cli zoxide starship
 
@@ -66,10 +67,11 @@ main() {
   export PATH="$HOME/.pixi/bin:$PATH"
   has_cmd dnf && system_install
   pixi_install
+  pixi_packages_install
   dotfiles_install
 
   has_cmd nu || die "nu is not installed. Quitting."
-  nu "${DOT_DIR}/setup.nu" fish
+  nu "${DOT_DIR}/setup.nu" fish 2>&1 | tee -a "${HOME}/.fedora-niri-config.log"
 }
 
 main "$@"
